services:
  seller:
    build:
      context: ..
      dockerfile: seller/Dockerfile
    ports:
      - "${SELLER_PORT:-3000}:80"
    depends_on:
      - seller-product
      - seller-inventory
    networks:
      - seller-network

  seller-product:
    build:
      context: ..
      dockerfile: seller-product-mfe/Dockerfile
    networks:
      - seller-network

  seller-inventory:
    build:
      context: ..
      dockerfile: seller-inventory-mfe/Dockerfile
    networks:
      - seller-network

networks:
  seller-network:
    name: "${DOCKER_NETWORK:-grab-dev-network}"
    external: true
