import type { CategoryLeavesResult, CreateProductMediaUploadRequest, CreateProductRequest, CreateSellableProductRequest, CreateSellableProductResponse, GetFullProductResponse, GetVariantResponse, GetVariationOptionResult, GetVariationTypeResult, UpdateProductRequest, UpdateProductResponse, UpdateSellableProductRequest, UpdateProductVariantRequest, UpdateProductVariantResponse, VariationMatrixRequest, VariationMatrixResponse, DeleteProductResponse, ProductMediaUploadResponse, ProductModerationResponse, ProductSearchRequest, ProductSearchResponse, ReplaceProductMediaRequest, ReplaceProductMediaResponse } from "@/features/products/types";
import type { HateoasLink } from "@khinemyaezin/seller-api";
export declare const catalogService: {
    createVariationMatrix: (link: HateoasLink, request: VariationMatrixRequest, headers?: Record<string, string>) => Promise<VariationMatrixResponse>;
    getCategories: (link: HateoasLink, headers?: Record<string, string>) => Promise<CategoryLeavesResult>;
    createProduct: (link: HateoasLink, request: CreateProductRequest, headers?: Record<string, string>) => Promise<void>;
    getVariationType: (link: HateoasLink, headers?: Record<string, string>) => Promise<GetVariationTypeResult>;
    getVariationOption: (link: HateoasLink, headers?: Record<string, string>) => Promise<GetVariationOptionResult>;
    searchProducts: (link: HateoasLink, request: ProductSearchRequest, headers?: Record<string, string>) => Promise<ProductSearchResponse>;
    getFullProduct: (link: HateoasLink, headers?: Record<string, string>) => Promise<GetFullProductResponse>;
    getVariant: (link: HateoasLink, headers?: Record<string, string>) => Promise<GetVariantResponse>;
    updateProduct: (link: HateoasLink, request: UpdateProductRequest, headers?: Record<string, string>) => Promise<UpdateProductResponse>;
    deleteProduct: (link: HateoasLink, headers?: Record<string, string>) => Promise<DeleteProductResponse>;
    restoreProduct: (link: HateoasLink, headers?: Record<string, string>) => Promise<ProductModerationResponse>;
    publishProduct: (link: HateoasLink, headers?: Record<string, string>) => Promise<ProductModerationResponse>;
    getCreateSellableProduct: (link: HateoasLink, headers?: Record<string, string>) => Promise<CreateSellableProductResponse>;
    createProductMediaUpload: (link: HateoasLink, request: CreateProductMediaUploadRequest, headers?: Record<string, string>) => Promise<ProductMediaUploadResponse>;
    replaceProductMedia: (link: HateoasLink, request: ReplaceProductMediaRequest, headers?: Record<string, string>) => Promise<ReplaceProductMediaResponse>;
    createSellableProduct: (link: HateoasLink, request: CreateSellableProductRequest, headers?: Record<string, string>) => Promise<CreateSellableProductResponse>;
    updateSellableProduct: (link: HateoasLink, request: UpdateSellableProductRequest, headers?: Record<string, string>) => Promise<CreateSellableProductResponse>;
    updateProductVariant: (link: HateoasLink, request: UpdateProductVariantRequest, headers?: Record<string, string>) => Promise<UpdateProductVariantResponse>;
    deleteProductVariant: (link: HateoasLink, headers?: Record<string, string>) => Promise<void>;
    restoreProductVariant: (link: HateoasLink, headers?: Record<string, string>) => Promise<void>;
};
